services:
  - type: web
    name: analyquizz
    runtime: python
    buildCommand: "pip install --upgrade pip && pip install --only-binary=:all: --no-compile --prefer-binary -r requirements.txt"
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: 1
      - key: PIP_NO_CACHE_DIR
        value: 1
      - key: PIP_ONLY_BINARY
        value: ":all:"
      - key: CARGO_HOME
        value: /tmp/cargo
      - key: MONGODB_URI
        fromDatabase:
          name: analyquizz-db
          property: connectionString